Section "Device"
    Identifier "Dummy"
    Driver "dummy"
    VideoRam 256000
EndSection

Section "Monitor"
    Identifier "Dummy Monitor"
    HorizSync 28-80
    VertRefresh 43-60
    Option "PreferredMode" "1920x1080"
EndSection

Section "Screen"
    Identifier "Dummy Screen"
    Device "Dummy"
    Monitor "Dummy Monitor"
    DefaultDepth 24
    SubSection "Display"
        Modes "1920x1080"
    EndSubSection
EndSection